### your site title here

title: Apoio ao BCC
baseurl: '/beta' # name of the repository
url: "http://bcc.ime.usp.br"
email: "Nathan Benedetto Proen√ßa"
destination: '/var/www/beta/'


highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
